services:
  django:
    build: ../backend
    container_name: storage_django
    env_file:
      - ../.env
    volumes:
      - static_volume:/app/staticfiles
      - ../media:/app/media

  nginx:
    image: nginx:1.19.3
    container_name: storage_nginx
    ports:
      - 99:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - ../media:/var/html/media/


volumes:
  static_volume:
  media_volume: