# Generated by Django 4.2.7 on 2023-11-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_boxx_boxx_boxx_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='photo_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
