# Generated by Django 4.2.7 on 2023-11-21 15:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_stock_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Необходима доставка?'),
        ),
    ]
